name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  # Update npm dependencies
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update dependencies
        run: |
          npx npm-check-updates -u
          npm install

      - name: Run tests after update
        run: |
          npx nx run-many --target=test --all --parallel
          npx nx run-many --target=lint --all --parallel

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          body: |
            ## Dependency Updates

            This PR updates the following dependencies:

            - Updated npm packages to their latest versions
            - All tests are passing
            - All linting checks are passing

            ### Changes
            - Updated dependencies in package.json
            - Updated package-lock.json

            Please review the changes and merge if everything looks good.
          branch: dependency-updates
          delete-branch: true

  # Security audit
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate

      - name: Fix security vulnerabilities
        run: npm audit fix --force
        continue-on-error: true

      - name: Create security fix PR
        if: failure()
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'security: fix vulnerabilities'
          title: 'security: fix vulnerabilities'
          body: |
            ## Security Fixes

            This PR fixes security vulnerabilities found in dependencies.

            ### Changes
            - Fixed security vulnerabilities
            - Updated vulnerable packages

            Please review the changes and merge if everything looks good.
          branch: security-fixes
          delete-branch: true

  # Check for outdated packages
  check-outdated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for outdated packages
        run: |
          echo "## Outdated Packages" >> $GITHUB_STEP_SUMMARY
          npm outdated >> $GITHUB_STEP_SUMMARY || true

      - name: Generate dependency report
        run: |
          npx npm-check-updates --format=json > outdated-packages.json
          echo "## Dependency Report" >> $GITHUB_STEP_SUMMARY
          echo "```json" >> $GITHUB_STEP_SUMMARY
          cat outdated-packages.json >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY

      - name: Upload dependency report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-report
          path: outdated-packages.json
          retention-days: 30
